
POST http://localhost:9090/account HTTP/1.1
content-type: application/json

{
    "firstName": "JWT",
    "lastName": "Test"
}


###

POST http://localhost:9090/login HTTP/1.1
content-type: application/json

{
    "number": 4567890,
    "password": "Testpassword"
}

###

get http://localhost:9090/account HTTP/1.1
content-type: application/json  

###

get http://localhost:9090/account/12 HTTP/1.1
content-type: application/json  
x-jwt-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50TnVtYmVyIjo4NDk4MDgxLCJleHBpcmVzQXQiOjE1MDAwfQ.DkQ7O_10WnExoVTQt1AKiS1rECVQiZWnm8DTlU508U8
###

delete http://localhost:9090/account/14 HTTP/1.1
content-type: application/json  

###

post http://localhost:9090/transfer HTTP/1.1
content-type: application/json  

{
    "toAccount": 3439,
    "amount": 8970
}


###

delete http://localhost:9090/account/2 HTTP/1.1
content-type: application/json  
x-jwt-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIiLCJuYmYiOjE0NDQ0Nzg0MDB9.u1riaD1rW97opCoAuRCTy4w58Br-Zk-bh7vLiRIsrpU